In [3]:
print("Hello, World")
print('Another Hello')

Hello, World
Another Hello


In [2]:
for i in range (4):
    print(i)

0
1
2
3


In [ ]:
x=7
y=7.0
print("x= ",x ,"it's type is ",type(x) ) # We use doble quotes as there is 's in it's
print("y= ",y ,"it's type is ",type(y) )

x=  7 it's type is  <class 'int'>
y=  7.0 it's type is  <class 'float'>


Another way more effecient for writing sentence with numbers by using Formats f ".

In [9]:
print(f"x = {x} and it's type is {type(x)}")

x = 7 and it's type is <class 'int'>


Sign "+" is used for 2 operations:

Add => if it applicates on numbers.

Concatenation => if it applicaties on strings

"Note that"

Concatenation can't be applied on different data types

In [ ]:
one=1
two=2
three=one +two
print(three)

hello="hello"
world="world"
helloworld=hello + " " + world  # here it will concatenate the two words together
print(helloworld)


3
hello world


WE can assign different values in the same line and do the printing too in the same line.

In [13]:
a,b,c=5,45,20
print(a,b,c)  # the output will be in the same line , if you need them in separete lines, do print for each variable.

5 45 20


if you assign values less than the variables mentiond like this:

x,r,e=5,4

it will give you error, but if otherwise means that you assigns values more than the mention variables it will consider them as a "*Tuple*".

In [ ]:
x=5,4,7
print(x) # here it will consider x as a tuple

(5, 4, 7)


Lists : here you can define a list without defining it's size , on despite the Array in other language. 

In [20]:
mylist=[]
mylist.append(3)
mylist.append(5)
mylist.append(30)
mylist.append(45)
print(mylist[0])
print(mylist[2])
print(mylist[3])

print("Print all values in the list by using loop...")
for i in mylist:
    print(i)

3
30
45
Print all values in the list by using loop...
3
5
30
45


Arithmatic Operations

In [ ]:
number = 1 + 5 * 4 / 3.0
print(number)

7.666666666666667


In [24]:
reminder=11%3
print(reminder)

2


In [25]:
quotes=11//3  # => 11/3=3*3+2 --> value= divisor * quotes + reminder
print(quotes)

3


In [26]:
power=6**3
print(power)

216


Using operators with strings.

As we mention above the concatenation.

Here another operators can be applied: *

sign "*" when used with strings , it means repeatting

In [27]:
helloamona="helloamona " * 3
print(helloamona)

helloamona helloamona helloamona 


*Using Operators with Lists*

sign "+" when used with lists, it will joined the lists together in one list.

sign "*" : it will be as same as it's using with the string " will repeates them as we say by using for example list5 * 3 --> it will repeates the values in these list 3 times."

In [31]:
list1=[1,2,5]
list2=[45,20,2]
list3 =list1+list2
print(list3)

[1, 2, 5, 45, 20, 2]


In [33]:
print(list1*3)

[1, 2, 5, 1, 2, 5, 1, 2, 5]


*Conditions*

In [34]:
x=2
print(x == 2) # True
print(x == 5) # False
print(x > -9) # True

True
False
True


Logical Operations Can be done by :

and  , or --> i mean it's written like this when using "in English"

The "in" Operator can be used to check if a specified object exists within an iterable objet container

In [ ]:
name="Eman"
print(name in ["Emaa","Eman"])

True


*LOOPS*

In [40]:
primes=[2,3,5,7]
for prime in primes:
    print(prime)

2
3
5
7


For loop using range function :

range(start,end, step): if you don't define the start it will be by default :0 and if you don't define the step it will be :1  

In [ ]:
for i in range(5):
    print(i) # It will print from 0 to 4

4


print values of 3,4,5

In [48]:
for h in range(3,6):
    print(h)

3
4
5


print values of 3,5,7

In [49]:
for j in range (3,8,2):
    print(j)

3
5
7


*While Loop*

It repeates the statments or output as long as the condition is true



print out from 0 to 5 using while loop

In [ ]:
count=0
while(count < 5):
    print(count)
    count += 1  # in python we can't apply increment like this ++ directly

0
1
2
3
4


"Break" and "Continue" Statements

break is used to exit from the loop, but continue is used to skip this output and go again to complete the loop




print out 0,1,2,3,4 using break statement

In [58]:
counts=0
while True:
    print(counts)
    counts += 1
    if(counts > 4):
        break

0
1
2
3
4


print only odd primes 1,3,5,7,9 using contiune statement

In [69]:
counter=0
while True:
    if counter % 2 == 0:
        counter += 1
        continue
    print(counter)
    counter += 1
    if counter > 9:
        break    


1
3
5
7
9


Another way for this will be with for loop

In [70]:
i=0
for i in range(10):
    if( i % 2 == 0):
        continue
    print(i)

1
3
5
7
9


*Functions*

Functions in python are defined using the block keyword "def"

In [ ]:
def myfunction():
    print("Hello Everyone from Eman Orabi :)")
# Calling the function
myfunction()    

Hello Everyone from Eman Orabi :)


Functions may also receive arguments (variable passed from the caller to the function)

In [79]:
def myfunction_with_args(username,greeting):
    print(f"Hello,{username} from my Function !! I wish you {greeting} ^_^")

In [80]:
myfunction_with_args("Eman","All the best")

Hello,Eman from my Function !! I wish you All the best ^_^


Functions may return a value to the caller, using the keyword "return"

In [81]:
def sum_two_numbers(num1,num2):
    return num1+num2

In [83]:
result=sum_two_numbers(5,40)
print("The result of the summation Function is ",result)

The result of the summation Function is  45


___Classes and Objects___

Objects are an encapsulation of variables and functions into a single entity. Objects get their functions from classes.
Classes are essentially a template to create your objects.

In [ ]:
class MyClass:
    variable="blaah"
    def function(self):
        print("This is a message inside the class")
# Take an object from the class
MyObject=MyClass()
print(MyObject.variable)  # For accessing anything inside the class will be by thr dot operator (.)
        

blaah


In [2]:
MyObject.function()

This is a message inside the class


__init()__

The __init__() function is a special function that is called when is being intiated. it's used for assigning values in a class

In [3]:
class NumberHolder:
    def __init__(self,number):
        self.number=number
    
    def returnNumber(self):
        return self.number
# Taking an object
var=NumberHolder(7) 
print(var.returnNumber())       

7


_____Dictionaries_____

A dictionary is a data type similar to arrays, but works with jeys and values instead of indexes. Each Values stored in the dictionary can be accessed using a key.

In [4]:
phonebook={}
phonebook["john"]=938477566
phonebook["jack"]=938477264
phonebook["harry"]=938477495
print(phonebook)

{'john': 938477566, 'jack': 938477264, 'harry': 938477495}


Another way to assign a dictionary

In [6]:
phonebook={
    "john":938477566,
    "jack":938477264,
    "harry":938477495
}
print(phonebook)

{'john': 938477566, 'jack': 938477264, 'harry': 938477495}


___Methods___ used with dictionary are:

.items()  => take all itemes  "key" : vlaue  and give you them as a collection of tuples.

.keys()   => take the key which will be inside "key" and give you them in one list

.values() => take the value which will be after conlons : value and also will return them in one list

In [12]:
phonebook.items()


dict_items([('john', 938477566), ('jack', 938477264), ('harry', 938477495)])

In [9]:
phonebook.keys()

dict_keys(['john', 'jack', 'harry'])

In [10]:
phonebook.values()

dict_values([938477566, 938477264, 938477495])

_____Modules and Packages_____

In programming, a module is a piece of software that has a specific functionality and it can be called by using "import" then the name of the package or the module.

In [14]:
import numpy

it can be abbreative by using the word "as" then the word you need

In [15]:
import numpy as np

To import all the functions inside the module , you can use "*"

In [16]:
from numpy import *

You also can import a specific functions from this, by calling their name directly.

In [17]:
from numpy import random, array

if you wanna to know all the functions which in any package or module you can use the function of dir().

In [23]:
import numpy as np
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

if you want to know how to use a specific function in the package, you can use the function of help()

In [25]:
print(help(np.array))

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

for any any array we should know three things:

values that i put into the array,dimensions and its data type
[values are putting here, for dimensions you can define it by using number of brackets [[],[],[]]--> something like this. and take argument of datatype by writing --> dtype = np.type you need, may be int8, int32,...  ] 

In [38]:
import numpy as np

x= np.array(
    [
        [1,2,3],
        [4,5,6]
    ],
            dtype=np.int8)

In [39]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

To know the dimension of the array or modify it , it will be by:

shape --> for knowing and reshape --> for modifying

In [40]:
x.shape

(2, 3)

In [53]:
x2=x.reshape(3,2)
x2

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int8)

In [54]:
print(f"x dimensions : {x.ndim} , x2 dimensions : {x2.ndim}")

x dimensions : 2 , x2 dimensions : 2


_____ravel()_____

is used to flatten the array, which means to make the array in one dimension.

In [57]:
x3=x.ravel()
x3.shape

(6,)

In [58]:
x3.ndim

1

_____________BroadCasting_____________

numpy accapet to make operations on different sizes by using the __Broadcating__ through adding values or something like what we use in image proceessing "__Padding__" to make them in the same size then make the operation

In [74]:
h=np.arange(5).reshape(1,1,5)
h.ndim

3

In [75]:
h

array([[[0, 1, 2, 3, 4]]])

In [76]:
x=5
x+h

array([[[5, 6, 7, 8, 9]]])